# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'function_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_function_window(object):
    def setupUi(self, function_window):
        function_window.setObjectName("function_window")
        function_window.resize(400, 500)
        function_window.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.centralwidget = QtWidgets.QWidget(function_window)
        self.centralwidget.setObjectName("centralwidget")
        self.recreate = QtWidgets.QPushButton(self.centralwidget)
        self.recreate.setGeometry(QtCore.QRect(280, 10, 111, 41))
        self.recreate.setObjectName("recreate")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(20, 30, 251, 391))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 10, 221, 41))
        font = QtGui.QFont()
        font.setFamily("微軟正黑體")
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 221, 31))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 191, 41))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(10, 170, 151, 51))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(10, 230, 171, 61))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(10, 280, 191, 41))
        self.label_6.setObjectName("label_6")
        function_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(function_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 21))
        self.menubar.setObjectName("menubar")
        function_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(function_window)
        self.statusbar.setObjectName("statusbar")
        function_window.setStatusBar(self.statusbar)

        self.retranslateUi(function_window)
        QtCore.QMetaObject.connectSlotsByName(function_window)

    def retranslateUi(self, function_window):
        _translate = QtCore.QCoreApplication.translate
        function_window.setWindowTitle(_translate("function_window", "MainWindow"))
        self.recreate.setText(_translate("function_window", "重新選取"))
        self.label.setText(_translate("function_window", "目前只有FA結束通知"))
        self.label_2.setText(_translate("function_window", "預計會有:"))
        self.label_3.setText(_translate("function_window", "掉落物統計"))
        self.label_4.setText(_translate("function_window", "四象EX+通知"))
        self.label_5.setText(_translate("function_window", "有想要的功能"))
        self.label_6.setText(_translate("function_window", "有問題 都告訴我"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    function_window = QtWidgets.QMainWindow()
    ui = Ui_function_window()
    ui.setupUi(function_window)
    function_window.show()
    sys.exit(app.exec_())
